name: Deploy to IIS

on: 
   push:
     branches:
       - "master"
     
jobs:
  build-and-deploy:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@master
    
    - name: Setup API
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
    
    # dotnet build and publish
    
    - name: Restore dependencies API
      run: dotnet restore
      
    - name: Build API
      run: dotnet build --configuration Release --no-restore CinemaBookingSystem.sln

    - name: Publish API
      run: |
        dotnet publish -c Release --output ./api CinemaBookingSystem.sln
    - name: Deploy API to IIS
      run: |
        iisreset /stop
        Copy-Item ./api/* C:/projects/api -Recurse -Force
        iisreset /start
    
     #Identity 
    - name: Setup Identity
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies Identity
      working-directory: ./IdentityServer
      run: dotnet restore

    # dotnet build and publish
    - name: Build Identity
      run: dotnet build --configuration Release --no-restore IdentityServer/IdentityServer.csproj

    - name: Publish Identity
      run: |
        dotnet publish -c Release --output .\identity IdentityServer/IdentityServer.csproj
    - name: Deploy Identity to IIS
      run: |
        iisreset /stop
        Copy-Item ./identity/* C:/projects/identity -Recurse -Force
        iisreset /start
    # Web-Public
    
    - name: Setup Web-Public
      uses: actions/setup-node@v3
      with:
          node-version: 16.13.1
          cache: 'npm'
          cache-dependency-path: "./CinemaBookingSystem.WebPublic/package-lock.json"
    
    - name: Install WebPublic
      working-directory: ./CinemaBookingSystem.WebPublic/
      run: npm --silent i
      
    - name: Build WebPublic
      working-directory: ./CinemaBookingSystem.WebPublic/
      run: npm run build
      
    - name: Deploy WebPublic to IIS
      working-directory: ./CinemaBookingSystem.WebPublic/
      run: |
        iisreset /stop
        Copy-Item ./dist/* C:/projects/web-public -Recurse -Force
        iisreset /start
        
    # Web-Admin
    
    - name: Setup Web-Admin   
      uses: actions/setup-node@v3
      with:
          node-version: 16.13.1
          cache: 'npm'
          cache-dependency-path: "./CinemaBookingSystem.WebAdmin/package-lock.json"
    
    - name: Install WebAdmin
      working-directory: ./CinemaBookingSystem.WebAdmin/
      run: npm --silent i
      
    - name: Build WebAdmin
      working-directory: ./CinemaBookingSystem.WebAdmin/
      run: npm run build
      continue-on-error: true
      
    - name: Deploy WebPublic to IIS
      working-directory: ./CinemaBookingSystem.WebAdmin/
      run: |
        iisreset /stop
        Copy-Item ./dist/* C:/projects/web-admin -Recurse -Force
        iisreset /start

